"""Core dataclasses passed around the engine."""
from __future__ import annotations

import time
from dataclasses import dataclass, field
from typing import Optional

from .enums import (
    IntentType,
    OrderSide,
    OrderStatus,
    OrderType,
    PositionSide,
)
from .instruments import Instrument, get_instrument

_id_counter = 0


def _next_id(prefix: str) -> str:
    global _id_counter
    _id_counter += 1
    return f"{prefix}-{_id_counter}"


@dataclass
class Bar:
    symbol: str
    ts: float           # epoch seconds (bar close time)
    open: float
    high: float
    low: float
    close: float
    volume: float = 0.0

    @property
    def is_up(self) -> bool:
        return self.close >= self.open


@dataclass
class Tick:
    symbol: str
    ts: float
    price: float
    size: float = 0.0


@dataclass
class Intent:
    """A strategy's expressed desire, before risk/sizing is applied."""
    type: IntentType
    reason: str = ""
    qty: Optional[int] = None   # strategy hint; risk manager may override


@dataclass
class Order:
    strategy_id: str
    symbol: str
    side: OrderSide
    qty: int
    type: OrderType = OrderType.MARKET
    price: Optional[float] = None
    stop_price: Optional[float] = None
    status: OrderStatus = OrderStatus.PENDING
    id: str = field(default_factory=lambda: _next_id("ORD"))
    ts: float = field(default_factory=time.time)
    reason: str = ""


@dataclass
class Fill:
    order_id: str
    strategy_id: str
    symbol: str
    side: OrderSide
    qty: int
    price: float
    commission: float = 0.0
    ts: float = field(default_factory=time.time)


@dataclass
class Position:
    """A single strategy's virtual position in one instrument.

    Multiple strategies can each hold their own virtual position; the broker /
    prop account nets them. Strategy-level positions exist for attribution so
    the dashboard can show per-strategy P/L.
    """
    symbol: str
    qty: int = 0                 # signed: + long, - short
    avg_price: float = 0.0
    realized_pnl: float = 0.0
    unrealized_pnl: float = 0.0
    last_price: float = 0.0

    @property
    def instrument(self) -> Instrument:
        return get_instrument(self.symbol)

    @property
    def side(self) -> PositionSide:
        if self.qty > 0:
            return PositionSide.LONG
        if self.qty < 0:
            return PositionSide.SHORT
        return PositionSide.FLAT

    @property
    def is_flat(self) -> bool:
        return self.qty == 0

    @property
    def is_long(self) -> bool:
        return self.qty > 0

    @property
    def is_short(self) -> bool:
        return self.qty < 0

    def mark(self, price: float) -> None:
        self.last_price = price
        if self.qty == 0:
            self.unrealized_pnl = 0.0
        else:
            self.unrealized_pnl = self.instrument.pnl(price - self.avg_price, self.qty)

    def apply_fill(self, side: OrderSide, qty: int, price: float) -> float:
        """Apply a fill, returning realized P/L generated by this fill (if any)."""
        signed = qty if side is OrderSide.BUY else -qty
        realized = 0.0
        instr = self.instrument

        if self.qty == 0 or (self.qty > 0) == (signed > 0):
            # Opening or adding in the same direction: weighted avg price.
            new_qty = self.qty + signed
            if new_qty != 0:
                self.avg_price = (
                    self.avg_price * abs(self.qty) + price * abs(signed)
                ) / abs(new_qty)
            self.qty = new_qty
        else:
            # Reducing / closing / flipping.
            closing = min(abs(signed), abs(self.qty))
            direction = 1 if self.qty > 0 else -1
            realized = instr.pnl((price - self.avg_price) * direction, closing)
            self.realized_pnl += realized
            self.qty += signed
            if self.qty == 0:
                self.avg_price = 0.0
            elif (self.qty > 0) != (direction > 0):
                # Flipped through zero: remainder opens a new position at price.
                self.avg_price = price
        self.mark(price)
        return realized


@dataclass
class Trade:
    """A completed round-trip for one strategy (entry → flat)."""
    strategy_id: str
    symbol: str
    direction: str          # "LONG" or "SHORT"
    qty: int
    entry_price: float
    exit_price: float
    entry_ts: float
    exit_ts: float
    pnl: float
    commission: float = 0.0
    id: str = field(default_factory=lambda: _next_id("TRD"))

    @property
    def is_win(self) -> bool:
        return self.pnl > 0

    @property
    def pnl_ticks(self) -> float:
        instr = get_instrument(self.symbol)
        delta = (self.exit_price - self.entry_price)
        if self.direction == "SHORT":
            delta = -delta
        return instr.ticks(delta)

    @property
    def duration_s(self) -> float:
        return max(0.0, self.exit_ts - self.entry_ts)


@dataclass
class AccountInfo:
    """REAL account data fetched from the connected provider. Every field here
    comes straight from the broker API — nothing is synthesized or estimated.
    Fields the provider doesn't return stay None so the UI shows '—', never a
    fabricated value."""
    provider: str
    account_id: str = ""
    name: str = ""
    balance: Optional[float] = None       # closed/cash balance
    equity: Optional[float] = None        # net liquidation (balance + open P/L)
    open_pnl: Optional[float] = None      # unrealized P/L on open positions
    day_pnl: Optional[float] = None       # realized+unrealized since session start
    can_trade: Optional[bool] = None
    currency: str = "USD"
    ts: float = field(default_factory=time.time)


@dataclass
class BrokerPosition:
    """A REAL open position as reported by the connected provider."""
    symbol: str
    qty: int                              # signed: + long, - short
    avg_price: Optional[float] = None
    open_pnl: Optional[float] = None

    @property
    def side(self) -> str:
        return "LONG" if self.qty > 0 else "SHORT" if self.qty < 0 else "FLAT"
